// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbwbyhkolvuxxsppwgtx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNid2J5aGtvbHZ1eHhzcHB3Z3R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNDQ4OTAsImV4cCI6MjA2MTkyMDg5MH0.QdMTesBhSf6eXoHIYOib9ejXd7dSGf1Hwo4Ul_oJS5o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);